version: '3.8'
services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/_frontend
      - media_volume:/usr/src/app/upload
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    build: .
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/_frontend
      - media_volume:/usr/src/app/upload
      - ./:/usr/src/app/
    expose:
      - "8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql_second_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: Sixfortypy_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: "1234"
    env_file:
      - ./.env.prod
    ports:
      - "3307:3306"
    volumes:
      - /path/to/your/mysql-data:/var/lib/mysql
    command: --bind-address=0.0.0.0
